version: '3'

services:
        jboss:
                image: tomcat
                container_name: kavya_tomcat
                ports:
                        - "8090:8080"

                volumes:
                        - kavya:/usr/local/tomcat/webapps
                networks:
                        - hima
                deploy:
                        replicas: 2


volumes:
        kavya:


networks:
        hima:

