version: '3'

services:

        tomcatnew:
                image: 13.127.33.147:8083/hima
                container_name: kavya_tomcat
                ports:
                        - "8090:8080"

                volumes:
                        - kavya:/usr/local/tomcat/webapps
                networks:
                        - hima

        jbossnew:

                image: 13.127.33.147:8083/kavya
                container_name: hima_jboss
                ports:
                     - "8089:8080"
                     - "9990:9990"
                volumes:
                        - wild:/opt/jboss/wildfly/standalone/deployments
                networks:
                        - jboss
volumes:
        kavya:
        wild:

networks:
        hima:
        jboss:


